version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfridoy-portfolio
    # restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
